<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>9b157937-f4da-4876-8852-589db1bdf10c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Odontosmart.Application\Odontosmart.Application.csproj" />
    <!-- Referenciado apenas para a composição de dependências em Program.cs. -->
    <ProjectReference Include="..\OdontoSmart.Infraestructure\OdontoSmart.Infraestructure.csproj" />
  </ItemGroup>

</Project>
